"""add google_id to user

Revision ID: 28c68693c9b3
Revises: 8ea5be077e1e
Create Date: 2026-04-15 10:08:08.189696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28c68693c9b3"
down_revision: Union[str, Sequence[str], None] = "8ea5be077e1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "user", sa.Column("google_id", sa.String(), nullable=True, unique=True)
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
