"""revert timestamp column change v2

Revision ID: 31d609f9530d
Revises: 8b752c4ee2c7
Create Date: 2026-02-25 16:46:31.688359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31d609f9530d"
down_revision: Union[str, Sequence[str], None] = "8b752c4ee2c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "location",
        "time",
        server_default=None,
        existing_type=sa.TIMESTAMP(timezone=True),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
