"""add created_at column in locations

Revision ID: 39e1fb3d472f
Revises: cb80519ba67d
Create Date: 2026-03-07 12:41:52.984221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "39e1fb3d472f"
down_revision: Union[str, Sequence[str], None] = "cb80519ba67d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM location")
    op.add_column(
        "location", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "created_at")
    # ### end Alembic commands ###
