"""rename 'workout_logs' to 'pause_resume_logs'

Revision ID: 3b30123a6da1
Revises: 8d6f34090f01
Create Date: 2026-03-12 11:01:08.274218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b30123a6da1"
down_revision: Union[str, Sequence[str], None] = "8d6f34090f01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE workout_logs RENAME TO pause_resume_logs")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TABLE pause_resume_logs RENAME TO workout_logs")
    # ### end Alembic commands ###
