"""generate timestamp in db

Revision ID: 4529f4f8a1ae
Revises: efc91c7c0252
Create Date: 2026-02-25 10:57:25.371194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "4529f4f8a1ae"
down_revision: Union[str, Sequence[str], None] = "efc91c7c0252"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("location", "time", server_default=text("NOW()"))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
