"""add user table and user_id foreign key in workout table

Revision ID: 454167a52b37
Revises: d33e00a459b9
Create Date: 2026-04-01 11:56:33.818959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "454167a52b37"
down_revision: Union[str, Sequence[str], None] = "d33e00a459b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM pause_resume_logs")
    op.execute("DELETE FROM workout")
    op.execute("DELETE FROM location")
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("workout", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "workout", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout", type_="foreignkey")
    op.drop_column("workout", "user_id")
    op.drop_table("user")
    # ### end Alembic commands ###
