"""rename workout table to location, and create a new table named 'Workout'

Revision ID: 49c50ba0a5d0
Revises: 8d8e2cc9c211
Create Date: 2026-02-24 13:49:28.190901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49c50ba0a5d0'
down_revision: Union[str, Sequence[str], None] = '8d8e2cc9c211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('workout', 'latitude')
    op.drop_column('workout', 'time')
    op.drop_column('workout', 'workout_id')
    op.drop_column('workout', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('workout', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('location')
    # ### end Alembic commands ###
