"""V2 db creates created_at values

Revision ID: 5916e77789f5
Revises: 40f1ed4b1428
Create Date: 2026-04-06 17:24:54.842364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5916e77789f5"
down_revision: Union[str, Sequence[str], None] = "40f1ed4b1428"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        server_default=sa.text("NOW()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###
