"""V3 db creates created_at values

Revision ID: 716d60ddb76f
Revises: 5916e77789f5
Create Date: 2026-04-06 17:30:31.539407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "716d60ddb76f"
down_revision: Union[str, Sequence[str], None] = "5916e77789f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("NOW()"),
    )
    op.alter_column(
        "user",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
