"""add workout logs table, and modify existing tables

Revision ID: 775d06479334
Revises: 39e1fb3d472f
Create Date: 2026-03-10 11:42:39.194457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "775d06479334"
down_revision: Union[str, Sequence[str], None] = "39e1fb3d472f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM workout")
    op.execute("DELETE FROM location")
    op.create_table(
        "workout_logs",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("paused_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("resumed_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workout.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "location", sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "location", sa.Column("deleted_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.create_foreign_key(None, "location", "workout", ["workout_id"], ["id"])
    op.add_column(
        "workout", sa.Column("started_at", postgresql.TIMESTAMP(), nullable=False)
    )
    op.add_column(
        "workout", sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.drop_column("workout", "resumed_at")
    op.drop_column("workout", "paused_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout",
        sa.Column(
            "paused_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "workout",
        sa.Column(
            "resumed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("workout", "updated_at")
    op.drop_column("workout", "started_at")
    op.drop_constraint(None, "location", type_="foreignkey")
    op.drop_column("location", "deleted_at")
    op.drop_column("location", "updated_at")
    op.drop_table("workout_logs")
    # ### end Alembic commands ###
