"""revert timestamp column change

Revision ID: 8b752c4ee2c7
Revises: 4529f4f8a1ae
Create Date: 2026-02-25 16:43:08.151040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b752c4ee2c7"
down_revision: Union[str, Sequence[str], None] = "4529f4f8a1ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "location",
        "time",
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
