"""created at column server default value

Revision ID: 8d6f34090f01
Revises: 775d06479334
Create Date: 2026-03-11 11:48:46.468792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = "8d6f34090f01"
down_revision: Union[str, Sequence[str], None] = "775d06479334"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workout",
        "created_at",
        server_default=func.now(),  # Or server_default=sa.text("CURRENT_TIMESTAMP")
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        "location",
        "created_at",
        server_default=func.now(),  # Or server_default=sa.text("CURRENT_TIMESTAMP")
        existing_type=sa.DateTime(),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
