"""add workout id to workout table

Revision ID: 8d8e2cc9c211
Revises: 9679a957edd4
Create Date: 2026-02-23 11:51:30.957022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8e2cc9c211'
down_revision: Union[str, Sequence[str], None] = '9679a957edd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workout_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'workout_id')
    # ### end Alembic commands ###
