"""rename name to username in user table

Revision ID: 8ea5be077e1e
Revises: 5c0e65d97f3f
Create Date: 2026-04-07 11:44:24.555697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea5be077e1e'
down_revision: Union[str, Sequence[str], None] = '5c0e65d97f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
