"""add created_at, paused_at, resumed_at, and deleted_at columns

Revision ID: cb80519ba67d
Revises: 133fe333d9b4
Create Date: 2026-03-07 12:04:19.453708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import delete

# revision identifiers, used by Alembic.
revision: str = "cb80519ba67d"
down_revision: Union[str, Sequence[str], None] = "133fe333d9b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE from workout")

    op.add_column(
        "workout", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False)
    )
    op.add_column(
        "workout", sa.Column("paused_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "workout", sa.Column("resumed_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "workout", sa.Column("stopped_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "workout", sa.Column("deleted_at", postgresql.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout", "deleted_at")
    op.drop_column("workout", "stopped_at")
    op.drop_column("workout", "resumed_at")
    op.drop_column("workout", "paused_at")
    op.drop_column("workout", "created_at")
    # ### end Alembic commands ###
