"""location table update column

Revision ID: d33e00a459b9
Revises: e53c119a7e75
Create Date: 2026-03-18 16:22:56.113712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func
from sqlalchemy.dialects.postgresql import TIMESTAMP

# revision identifiers, used by Alembic.
revision: str = "d33e00a459b9"
down_revision: Union[str, Sequence[str], None] = "e53c119a7e75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "location",
        "updated_at",
        server_default=func.now(),
        existing_type=TIMESTAMP(timezone=True),  # Specify the existing type
        existing_nullable=True,  # Specify existing nullable status
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
