"""correct completed status default value in workout table

Revision ID: efc91c7c0252
Revises: fbec339d82f7
Create Date: 2026-02-24 14:38:45.411617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efc91c7c0252"
down_revision: Union[str, Sequence[str], None] = "fbec339d82f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workout", "completed", server_default=sa.sql.false())
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
