"""ad completed status to workout table

Revision ID: fbec339d82f7
Revises: 49c50ba0a5d0
Create Date: 2026-02-24 14:35:50.900372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbec339d82f7"
down_revision: Union[str, Sequence[str], None] = "49c50ba0a5d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout",
        sa.Column(
            "completed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout", "completed")
    # ### end Alembic commands ###
